import React from 'react';
import { Calendar, Clock, AlertCircle } from 'lucide-react';

export default function StudyPlanView({ plan }: { plan: any }) {
  if (!plan) {
    return (
      <div style={{ padding: '48px', textAlign: 'center', color: 'var(--text-secondary)' }}>
        <Calendar size={48} style={{ opacity: 0.2, margin: '0 auto 16px' }} />
        <h3>No Study Plan Generated</h3>
        <p style={{ marginTop: '8px', fontSize: '0.9em' }}>Ask the assistant to create a study plan for your target companies.</p>
      </div>
    );
  }

  return (
    <div className="animate-in glass-panel" style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h2>Your Study Plan</h2>
        <div style={{ fontSize: '0.85em', color: 'var(--text-secondary)' }}>
          Generated by Planner Agent
        </div>
      </div>

      {plan.tasks && plan.tasks.length > 0 ? (
        <div style={{ display: 'grid', gap: '16px' }}>
          {plan.tasks.map((task: any, i: number) => (
            <div key={i} style={{ 
              background: 'var(--bg-glass-hover)', 
              borderRadius: '12px', 
              border: `1px solid ${task.priority === 'High' ? 'rgba(239,68,68,0.3)' : 'var(--border-glass)'}`,
              padding: '20px',
              position: 'relative',
              overflow: 'hidden'
            }}>
              {task.priority === 'High' && (
                <div style={{ position: 'absolute', top: 0, left: 0, width: '4px', height: '100%', background: 'var(--danger)' }} />
              )}
              
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '12px' }}>
                <h3 style={{ fontSize: '1.1em', margin: 0, paddingLeft: task.priority === 'High' ? '8px' : 0 }}>{task.topic}</h3>
                <span style={{ 
                  background: task.priority === 'High' ? 'rgba(239,68,68,0.2)' : 'rgba(255,255,255,0.1)', 
                  color: task.priority === 'High' ? '#fca5a5' : 'var(--text-secondary)', 
                  padding: '4px 10px', borderRadius: '12px', fontSize: '0.75em', fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase'
                }}>
                  {task.priority} Priority
                </span>
              </div>
              
              <div style={{ display: 'flex', gap: '16px', marginBottom: '16px', color: 'var(--text-secondary)', fontSize: '0.85em' }}>
                <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Clock size={14} /> {task.estimated_hours} hours</span>
                {task.target_date && <span>Target: {task.target_date}</span>}
              </div>
              
              <p style={{ margin: 0, fontSize: '0.9em', color: 'var(--text-primary)', lineHeight: 1.5 }}>
                {task.rationale}
              </p>
              
              {/* Highlight if priority was adjusted due to struggle */}
              {task.priority === 'High' && task.rationale.toLowerCase().includes('struggle') && (
                <div style={{ marginTop: '16px', background: 'rgba(245,158,11,0.1)', border: '1px solid rgba(245,158,11,0.2)', padding: '8px 12px', borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px', color: '#fcd34d', fontSize: '0.85em' }}>
                  <AlertCircle size={16} /> Adjusted by Adaptive Planner based on recent performance
                </div>
              )}
            </div>
          ))}
        </div>
      ) : (
        <div style={{ color: 'var(--text-secondary)' }}>No tasks in current plan.</div>
      )}
    </div>
  );
}
